image: archlinux
packages:
  - sdl
  - roswell
sources:
  - git@git.sr.ht:~jean-max/swarm
secrets:
  - ed142522-17bb-4d9f-ac0e-3be58c6d78ac
environment:
  PROJECT: swarm

tasks:
  - checkout: |
      cd $PROJECT
      LAST_COMMIT_HASH=$(git log --remotes | head -n1 | cut -d' ' -f2)
      git checkout $LAST_COMMIT_HASH

  - sbcl: |
      ros init
      mkdir -pv ~/common-lisp
      ln -sv ~/$PROJECT ~/common-lisp/$PROJECT

  - build: |
      cd $PROJECT
      make
      ls -lh $PROJECT

  - test: |
      cd $PROJECT
      make todo || true
      make test

  - run: |
      cd $PROJECT
      # timeout 10 ./$PROJECT || test $? = 124
      ./$PROJECT |& grep -q 'Cannot initialize the video subsystem.'
      ./$PROJECT.ros |& grep -q 'Cannot initialize the video subsystem.'
